# Hi there, I'm Kiruthika! 👋

I'm a Data Analyst with a passion for data visualization and analysis. Currently, I'm enhancing my skills in Power BI and MySQL.

## About Me
- 🔭 I’m currently working on projects using Power BI and MySQL.
- 🌱 I’m currently learning Data Analytics with Zukun.
- 💬 Ask me about MySQL, Data Analytics, and Power BI.
- 📫 How to reach me: kiruthikasivakumar247@gmail.com


## Skills
- MySQL
- Power BI
- Data Analysis

Feel free to check out my repositories and connect with me!
